title: 'schledererj.github.io'
description: "Personal website for Jack Schlederer"
baseurl: "/"
url: "https://schledererj.github.io"

header_pages:
  - index.md
  - contact.md

style: dark

# Build settings
markdown: kramdown
theme: jekyll-shell-theme

exclude:
  - local_cache/

host: 0.0.0.0